# Generated by Django 5.2.3 on 2025-06-23 10:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KvSecretPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KvSecretVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 23, 10, 53, 56, 990907))),
                ('deleted', models.BooleanField(default=False)),
                ('secret_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kv.kvsecretpath')),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['secret_path'], name='kv_kvsecret_secret__0e6d47_idx')],
                'unique_together': {('secret_path', 'version')},
            },
        ),
    ]
