# Generated by Django 5.2.3 on 2025-06-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SealStaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealed', models.BooleanField(default=False)),
                ('threshold', models.IntegerField()),
                ('share', models.IntegerField()),
                ('encrypted_root_token', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 6, 22, 7, 29, 9, 858046))),
            ],
        ),
    ]
