# Generated by Django 5.2.3 on 2025-06-22 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unsealapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal', models.BooleanField(default=False)),
                ('threshold', models.IntegerField()),
                ('share', models.IntegerField(default=0)),
                ('unseal_key', models.JSONField(default=list)),
                ('root_token', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 22, 17, 34, 11, 883182))),
            ],
        ),
    ]
