# Generated by Django 5.2.3 on 2025-06-23 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsealapi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealstatus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 10, 6, 47, 40851)),
        ),
    ]
