# Generated by Django 5.2.3 on 2025-06-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wraping_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrap_key', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2025, 6, 22, 7, 29, 9, 858268))),
            ],
        ),
    ]
